theme: jekyll-theme-cayman
markdown: kramdown
title: Hannah Sherwood
Description: Hi I'm Hannah! I'm a PhD student at the University of Leeds. This site is a portfolio of my work contributing towards the module'Programming for Geographical Information Analysis: Core Skills' with the School of Geography. 


